% H is the 4 × 4 homogeneous transformation matrix 
% containing the desired position and orientation of the end effector.
% myrobot is the robot structure generated by function mypuma560.

% returns q, the 1 × 6 vector of joint angles solving the inverse kinematics problem

function q = inverse_kuka(H,myrobot)

    % obtain values from H
    o_0d = H.t;
    R_d = H.R;

    % formula for o_0c
    o_0c = o_0d - R_d*[myrobot.a(6) 0 myrobot.d(6)]';

    % variables to extract coords
    x_c = o_0c(1);
    y_c = o_0c(2);
    z_c = o_0c(3);

    % general values 
    r = sqrt(x_c^2 + y_c^2) - myrobot.a(1);
    s = z_c - myrobot.d(1);
    b = sqrt(myrobot.a(3)^2+myrobot.d(4)^2);
    beta = atan2(myrobot.a(3), myrobot.d(4));

    theta_1 = atan2(y_c, x_c);

    D = (s^2 + r^2 - b^2 - myrobot.a(2)^2)/(2*b*myrobot.a(2));
    theta_3 = atan2(D, sqrt(1-D^2)) - beta;

    theta_2 = atan2(s, r) - atan2(b * sin(theta_3 + beta - pi/2), myrobot.a(2) + b * cos(theta_3 + beta - pi/2));

    H_03 = myrobot.A(1:3, [theta_1 theta_2 theta_3;]);
    R_03 = H_03.R;

    %calculate r
    R_36 = R_03'*R_d;

    theta_4 = atan2(R_36(2,3), R_36(1,3));
    theta_5 = atan2(real(sqrt(1-R_36(3,3)^2)), R_36(3,3));
    theta_6 = atan2(R_36(3,2), -R_36(3,1));

    q = [theta_1; theta_2; theta_3; theta_4; theta_5; theta_6]';
end