% joint is a 6  1 vector containing the values of the six joint angles.
% myrobot is the robot structure generated by function mypuma560.

% returns H, the homogeneous transformation matrix H06 = A1(theta_1).. A6(theta_6).

function H = forward(joint,myrobot,i)
    %display(joint')
    H = myrobot.A(1:i, joint');

    % compute H manually w/o .A
end